# Application
spring.application.name=TankIQ
spring.application.description=TankIQ API
spring.application.version=1.0.0

# Active profile
spring.profiles.active=dev

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
